version: "3.9"
services:
  postgres:
    container_name: pg
    restart: always
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres:/data/postgres
      - ./db/db-dump.sql:/docker-entrypoint-initdb.d/init_dump.sql
    ports:
      - 5431:5432

  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  front:
    container_name: front
    restart: always


volumes:
  postgres:
  pgadmin: